const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SUPER_DISTRIBUTOR: "SUPER_DISTRIBUTOR",
  DISTRIBUTOR: "DISTRIBUTOR",
  RETAILER: "RETAILER",
  USER: "USER",
};

const ROLE_ORDER = [
  ROLES.SUPER_ADMIN,
  ROLES.SUPER_DISTRIBUTOR,
  ROLES.DISTRIBUTOR,
  ROLES.RETAILER,
  ROLES.USER,
];

const CHILD_ROLES = {
  SUPER_ADMIN: [
    ROLES.SUPER_DISTRIBUTOR,
    ROLES.DISTRIBUTOR,
    ROLES.RETAILER,
    ROLES.USER,
  ],
  SUPER_DISTRIBUTOR: [ROLES.DISTRIBUTOR],
  DISTRIBUTOR: [ROLES.RETAILER],
  RETAILER: [ROLES.USER],
  USER: [],
};

module.exports = { ROLES, ROLE_ORDER, CHILD_ROLES };
